# Site settings
title: Translational lymphoma research in the Morin laboratory at Simon Fraser University
lab_name: TR Lab
author: >
  Dr. Sherry Chan
institution: HKU
email: kwsherry@hku.hk
description: >
  The TR Lab at the University of Hong Kong examines treatment-resistant schizophrenia and first episodes of psychosis. 
baseurl: ""
url: "https://TRLabWebsite.github.io"
github_username:  morinlab
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
